apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: YWRtaW4=  # Base64-encoded value of the username 'admin'
  mongo-root-password: cGFzc3dvcmQ=  # Base64-encoded value of the password 'password'
